def part_1
  contains(inputs, [], 'shiny gold').size
end

def part_2
  counts(inputs, 1, "shiny gold".to_sym) - 1
end

def contains(data, already_found, entry)
  new_found = data.select { |key, value| value.join(',').match(/#{entry}/) }.keys - already_found
  res = new_found.map { |item| contains(data, already_found, item.to_s) }

  (already_found + new_found + res).flatten.uniq
end

def counts(data, quantity, entry)
  bags_inside = 0

  if data[entry] != ["no other bags"]
    bags_inside += data[entry].map do |row|
      counts(data, row.split(' ', 2)[0].to_i, row.split(' ', 2)[1].gsub(/ bag(s)?/, '').to_sym)
    end.reduce(:+)
  end

  bags_inside*quantity + quantity
end

def short_inputs
  {
    "light red":["1 bright white bag", "2 muted yellow bags"],
    "dark orange":["3 bright white bags", "4 muted yellow bags"],
    "bright white":["1 shiny gold bag"],
    "muted yellow":["2 shiny gold bags", "9 faded blue bags"],
    "shiny gold":["1 dark olive bag", "2 vibrant plum bags"],
    "dark olive":["3 faded blue bags", "4 dotted black bags"],
    "vibrant plum":["5 faded blue bags", "6 dotted black bags"],
    "faded blue":["no other bags"],
    "dotted black":["no other bags"]
  }
end

def inputs
{
"mirrored beige":["1 drab brown bag", "3 dotted crimson bags"],
"light lavender":["5 clear teal bags", "2 wavy gold bags", "5 drab maroon bags", "2 posh cyan bags"],
"drab gold":["2 posh aqua bags", "3 dark olive bags"],
"plaid lime":["5 posh purple bags"],
"pale brown":["2 dotted teal bags", "4 light plum bags"],
"vibrant orange":["3 dim cyan bags", "1 shiny gold bag", "1 shiny salmon bag"],
"dull olive":["5 wavy yellow bags", "5 striped crimson bags", "2 dotted maroon bags"],
"dull violet":["1 posh orange bag", "2 muted plum bags", "2 mirrored bronze bags", "2 dull chartreuse bags"],
"shiny maroon":["5 wavy gold bags", "2 striped coral bags", "1 muted silver bag"],
"clear red":["5 plaid lavender bags"],
"dull blue":["3 plaid crimson bags"],
"faded black":["5 dull orange bags"],
"clear aqua":["4 dull white bags", "4 dotted cyan bags"],
"pale tomato":["3 bright beige bags"],
"drab yellow":["1 muted aqua bag", "5 dull purple bags", "5 light chartreuse bags"],
"muted yellow":["1 vibrant lavender bag", "3 vibrant cyan bags", "2 faded gray bags"],
"bright lime":["3 dull gray bags", "2 vibrant bronze bags", "4 light purple bags", "1 wavy gray bag"],
"vibrant bronze":["5 plaid blue bags", "2 plaid beige bags"],
"posh teal":["3 wavy magenta bags", "4 muted bronze bags"],
"muted indigo":["3 dark black bags", "3 mirrored orange bags", "2 clear crimson bags"],
"dull beige":["4 dim tan bags", "2 posh blue bags", "1 dull silver bag", "2 bright chartreuse bags"],
"posh magenta":["4 light brown bags"],
"vibrant olive":["2 vibrant purple bags", "3 dull gold bags", "1 clear olive bag", "3 clear plum bags"],
"bright beige":["5 faded teal bags", "3 light bronze bags", "5 vibrant yellow bags"],
"posh gray":["2 clear magenta bags", "2 wavy white bags", "2 mirrored olive bags", "2 vibrant violet bags"],
"dim gray":["5 plaid gold bags", "4 bright teal bags", "5 light indigo bags", "4 wavy salmon bags"],
"clear indigo":["3 striped salmon bags", "5 plaid maroon bags", "3 pale beige bags", "4 pale chartreuse bags"],
"dark coral":["1 dotted olive bag", "4 faded salmon bags"],
"faded green":["3 muted purple bags", "3 striped salmon bags", "1 mirrored aqua bag", "1 faded bronze bag"],
"muted blue":["5 drab white bags", "5 muted tomato bags", "1 dark brown bag"],
"dark lime":["3 striped blue bags", "5 dark silver bags", "4 bright red bags", "1 plaid crimson bag"],
"muted orange":["3 dark violet bags", "2 shiny tan bags"],
"muted lavender":["2 vibrant lime bags", "5 dotted white bags", "3 posh plum bags", "5 plaid blue bags"],
"light olive":["4 posh tomato bags", "2 pale chartreuse bags", "3 mirrored teal bags"],
"shiny crimson":["4 dim red bags", "1 vibrant crimson bag", "5 dim cyan bags", "3 faded silver bags"],
"wavy salmon":["2 muted olive bags"],
"light red":["5 wavy tomato bags", "3 clear fuchsia bags", "2 wavy blue bags", "2 vibrant fuchsia bags"],
"vibrant violet":["5 wavy red bags"],
"vibrant green":["2 wavy maroon bags", "5 wavy black bags", "1 dark bronze bag", "1 light cyan bag"],
"dull black":["3 mirrored white bags", "1 dim lavender bag", "1 faded blue bag"],
"shiny yellow":["1 dotted plum bag"],
"striped white":["2 pale salmon bags", "2 shiny white bags", "2 dark gray bags", "2 pale orange bags"],
"posh yellow":["4 dotted tan bags", "3 clear coral bags", "5 wavy magenta bags", "4 striped white bags"],
"dark red":["1 dotted olive bag", "2 posh orange bags", "3 striped gold bags"],
"wavy black":["1 bright cyan bag", "4 muted orange bags"],
"dull white":["4 pale red bags", "1 light lavender bag"],
"mirrored tomato":["1 dark green bag", "4 light yellow bags", "1 muted tan bag"],
"dim gold":["3 vibrant white bags"],
"dim plum":["4 light red bags"],
"pale lime":["1 pale maroon bag", "2 bright magenta bags", "5 mirrored purple bags"],
"light magenta":["2 bright maroon bags"],
"wavy gray":["5 shiny violet bags", "3 plaid bronze bags", "2 pale salmon bags", "2 mirrored maroon bags"],
"light brown":["5 muted tomato bags", "1 dull green bag", "2 wavy turquoise bags"],
"clear teal":["2 muted olive bags", "1 dull purple bag", "2 bright magenta bags"],
"plaid maroon":["5 light plum bags", "2 muted aqua bags", "2 light chartreuse bags", "1 dim tomato bag"],
"dotted salmon":["5 dark brown bags", "2 mirrored gold bags"],
"light orange":["4 muted aqua bags", "3 light plum bags"],
"vibrant blue":["1 wavy yellow bag"],
"dark white":["3 shiny magenta bags"],
"muted red":["2 faded violet bags"],
"vibrant crimson":["5 striped gold bags", "5 striped white bags", "4 bright lavender bags"],
"dim brown":["5 dotted olive bags", "2 striped white bags", "3 shiny black bags", "5 striped beige bags"],
"wavy indigo":["1 dim brown bag", "2 plaid yellow bags", "1 faded yellow bag"],
"dim coral":["5 light orange bags", "3 bright red bags", "1 wavy turquoise bag", "2 pale maroon bags"],
"mirrored salmon":["1 drab blue bag", "3 muted bronze bags", "1 muted brown bag"],
"striped olive":["1 dim bronze bag"],
"bright tan":["5 dark brown bags"],
"drab violet":["5 mirrored plum bags", "2 mirrored purple bags"],
"dark purple":["3 striped yellow bags", "1 pale orange bag", "4 dull fuchsia bags", "5 faded silver bags"],
"striped tan":["3 shiny salmon bags", "5 striped brown bags", "1 light gray bag"],
"posh aqua":["1 striped crimson bag"],
"mirrored black":["2 pale crimson bags", "3 posh lavender bags"],
"faded indigo":["5 dotted purple bags", "5 bright green bags"],
"dim aqua":["3 muted coral bags", "3 shiny fuchsia bags", "2 light indigo bags", "5 muted cyan bags"],
"dim bronze":["2 faded tomato bags", "4 faded tan bags", "5 dull teal bags"],
"dotted green":["1 vibrant gray bag", "4 wavy silver bags", "2 posh lavender bags", "3 wavy magenta bags"],
"faded gold":["5 pale salmon bags", "2 wavy silver bags", "2 bright olive bags", "2 plaid blue bags"],
"muted plum":["1 light fuchsia bag", "2 posh silver bags", "5 mirrored lime bags", "5 faded silver bags"],
"striped green":["1 plaid gray bag"],
"posh turquoise":["4 drab maroon bags"],
"dim violet":["no other bags"],
"striped violet":["5 pale aqua bags", "2 wavy coral bags"],
"dotted yellow":["2 faded lime bags", "4 dull turquoise bags"],
"muted aqua":["no other bags"],
"wavy maroon":["2 dim fuchsia bags", "4 mirrored teal bags", "1 muted brown bag", "2 muted gray bags"],
"clear maroon":["4 dotted maroon bags", "4 pale blue bags"],
"dim red":["1 pale lime bag", "4 dim cyan bags"],
"dark maroon":["4 dark silver bags", "2 pale indigo bags"],
"faded red":["1 faded black bag", "4 bright orange bags", "1 posh gray bag", "1 striped crimson bag"],
"dark turquoise":["3 vibrant tan bags", "4 pale brown bags"],
"pale gray":["3 dark gray bags", "1 wavy red bag", "1 dark plum bag"],
"shiny teal":["5 light yellow bags", "3 striped beige bags", "5 plaid red bags", "2 faded maroon bags"],
"posh indigo":["3 posh cyan bags", "2 bright lavender bags"],
"striped chartreuse":["4 dim maroon bags", "1 pale coral bag", "2 bright plum bags", "3 clear black bags"],
"faded violet":["5 dark purple bags", "2 plaid tan bags", "4 faded yellow bags", "1 faded salmon bag"],
"clear gray":["3 light lavender bags"],
"muted brown":["3 pale orange bags", "2 bright lavender bags", "3 clear red bags", "1 dark tan bag"],
"dotted gold":["2 plaid aqua bags", "3 pale fuchsia bags", "4 mirrored blue bags", "2 dull maroon bags"],
"dark yellow":["3 dotted maroon bags", "2 wavy coral bags"],
"dull tan":["2 plaid indigo bags", "3 dotted gray bags"],
"muted salmon":["4 dim lime bags"],
"clear turquoise":["3 mirrored green bags"],
"dark chartreuse":["2 vibrant coral bags"],
"plaid green":["5 pale indigo bags", "2 faded blue bags", "2 bright lavender bags", "1 drab indigo bag"],
"dim black":["5 light tomato bags"],
"posh blue":["1 dull lime bag", "1 posh maroon bag", "5 dim tomato bags"],
"bright violet":["3 dim black bags", "4 faded red bags", "5 bright salmon bags", "3 vibrant tomato bags"],
"faded plum":["4 clear teal bags", "1 faded lavender bag", "3 wavy crimson bags", "4 drab salmon bags"],
"bright fuchsia":["2 vibrant teal bags"],
"posh olive":["3 dotted gray bags"],
"muted black":["2 dotted coral bags", "5 dotted lime bags", "5 pale teal bags", "4 light plum bags"],
"mirrored coral":["4 drab yellow bags", "2 muted olive bags", "2 dotted teal bags"],
"muted lime":["1 clear white bag", "1 striped yellow bag", "1 vibrant silver bag", "4 striped violet bags"],
"dark teal":["3 light plum bags", "5 posh salmon bags", "2 posh white bags"],
"muted magenta":["5 faded gray bags", "1 clear red bag", "3 muted maroon bags"],
"bright indigo":["4 pale chartreuse bags", "3 faded blue bags"],
"striped crimson":["3 dotted red bags", "5 dark tan bags", "2 plaid lime bags"],
"clear yellow":["5 dark bronze bags", "1 mirrored olive bag"],
"dark olive":["5 striped gold bags", "1 faded bronze bag", "5 wavy blue bags", "3 bright lavender bags"],
"clear black":["5 vibrant white bags", "3 wavy white bags", "1 mirrored black bag"],
"wavy tan":["5 vibrant gray bags", "2 shiny salmon bags", "5 posh purple bags", "5 shiny white bags"],
"light tomato":["5 striped blue bags", "3 posh cyan bags"],
"dull chartreuse":["4 dim white bags", "5 faded violet bags", "1 mirrored coral bag"],
"mirrored gold":["1 drab white bag"],
"striped gray":["3 mirrored teal bags"],
"striped fuchsia":["2 dotted lime bags", "5 clear olive bags", "3 dotted yellow bags"],
"muted gold":["1 dark olive bag", "3 posh plum bags", "5 muted magenta bags", "1 light lavender bag"],
"striped silver":["1 dark brown bag", "2 drab salmon bags"],
"plaid bronze":["3 light plum bags", "4 plaid lime bags", "2 faded orange bags", "1 mirrored coral bag"],
"pale tan":["5 posh gray bags", "4 dotted violet bags", "5 posh fuchsia bags", "5 light silver bags"],
"dotted tomato":["3 vibrant white bags", "2 posh yellow bags"],
"pale maroon":["4 dotted teal bags", "5 bright olive bags", "4 striped gold bags", "4 bright lavender bags"],
"pale coral":["5 dull cyan bags", "1 muted aqua bag", "1 dull lime bag", "1 pale orange bag"],
"drab blue":["4 shiny olive bags", "5 faded maroon bags"],
"dull turquoise":["2 muted olive bags", "4 pale green bags"],
"dotted violet":["3 plaid tan bags", "5 wavy turquoise bags", "1 plaid maroon bag"],
"shiny chartreuse":["1 mirrored silver bag"],
"clear crimson":["5 bright plum bags", "2 muted silver bags"],
"faded tan":["4 pale indigo bags", "3 wavy red bags", "5 light gold bags"],
"light black":["4 dark aqua bags"],
"plaid yellow":["2 pale silver bags", "1 wavy blue bag", "4 bright lavender bags"],
"faded silver":["5 clear tan bags"],
"light yellow":["1 pale beige bag"],
"drab bronze":["4 pale maroon bags", "5 faded tomato bags", "1 vibrant crimson bag", "4 dull indigo bags"],
"dark plum":["2 dark gray bags", "1 pale chartreuse bag"],
"muted green":["1 dull gray bag", "1 light purple bag"],
"clear white":["5 dotted plum bags", "2 light orange bags"],
"faded chartreuse":["1 dim crimson bag", "1 light gray bag"],
"mirrored aqua":["2 dim teal bags", "4 muted silver bags", "1 striped salmon bag"],
"light bronze":["5 pale purple bags", "1 faded teal bag"],
"mirrored indigo":["1 wavy red bag", "5 faded tomato bags"],
"plaid chartreuse":["5 bright cyan bags"],
"light fuchsia":["5 faded violet bags"],
"mirrored orange":["1 drab lavender bag"],
"light indigo":["5 wavy plum bags", "5 vibrant chartreuse bags"],
"posh black":["1 dull brown bag"],
"mirrored yellow":["2 shiny gray bags"],
"bright white":["2 shiny silver bags", "1 dotted lime bag"],
"dark brown":["5 bright magenta bags", "1 striped beige bag", "5 pale beige bags"],
"faded lavender":["3 faded gold bags", "3 vibrant crimson bags", "2 pale aqua bags"],
"dotted cyan":["5 drab salmon bags", "5 clear blue bags", "3 wavy blue bags", "3 posh cyan bags"],
"clear coral":["2 light indigo bags"],
"plaid tan":["3 vibrant teal bags", "4 mirrored gold bags"],
"striped magenta":["4 posh magenta bags", "4 dim chartreuse bags", "1 muted lime bag", "4 vibrant aqua bags"],
"pale red":["5 dull plum bags", "3 wavy blue bags", "4 pale beige bags"],
"posh cyan":["5 shiny white bags", "4 muted coral bags", "2 pale chartreuse bags", "2 dark gray bags"],
"posh tan":["1 plaid tan bag", "5 dim tan bags"],
"dotted coral":["5 pale plum bags", "1 dull olive bag", "4 light gray bags", "3 pale yellow bags"],
"shiny silver":["3 dull teal bags", "2 dotted teal bags", "2 bright magenta bags"],
"drab white":["5 dark violet bags"],
"plaid teal":["2 pale green bags", "4 dim cyan bags", "1 drab white bag", "3 dull salmon bags"],
"faded magenta":["1 posh blue bag", "4 clear coral bags"],
"muted fuchsia":["1 faded aqua bag", "4 mirrored magenta bags", "2 wavy purple bags"],
"dark lavender":["5 dull fuchsia bags", "1 dull salmon bag", "3 plaid blue bags"],
"bright magenta":["3 shiny white bags", "4 pale chartreuse bags", "3 drab yellow bags", "1 dull purple bag"],
"vibrant lime":["4 striped coral bags", "3 shiny salmon bags", "3 light lime bags", "5 dark tan bags"],
"vibrant beige":["2 mirrored turquoise bags", "4 dim orange bags", "4 muted green bags"],
"drab brown":["4 plaid gray bags"],
"dotted plum":["4 dark plum bags", "3 pale brown bags"],
"vibrant turquoise":["4 dark purple bags"],
"dark silver":["3 faded blue bags", "4 dim aqua bags", "5 plaid turquoise bags", "1 bright cyan bag"],
"posh silver":["4 faded tomato bags", "2 muted olive bags"],
"drab beige":["1 pale beige bag"],
"mirrored brown":["2 posh olive bags", "4 vibrant teal bags", "5 pale red bags"],
"plaid black":["1 clear teal bag", "3 shiny crimson bags"],
"shiny violet":["3 mirrored white bags"],
"wavy fuchsia":["3 wavy gold bags"],
"bright gold":["1 dark violet bag", "5 dark beige bags", "2 bright salmon bags"],
"light gold":["5 bright magenta bags", "3 dim violet bags", "1 light lavender bag", "2 shiny white bags"],
"dark orange":["5 muted olive bags"],
"dull gold":["1 light tomato bag", "4 striped lavender bags", "2 shiny tomato bags", "2 plaid lime bags"],
"mirrored crimson":["4 plaid crimson bags", "4 shiny cyan bags", "2 bright cyan bags"],
"dim tan":["3 striped tan bags", "5 plaid crimson bags"],
"shiny turquoise":["5 light chartreuse bags", "2 pale chartreuse bags", "4 dotted teal bags"],
"wavy beige":["5 pale aqua bags", "2 pale brown bags"],
"shiny orange":["1 dotted gray bag", "1 plaid chartreuse bag", "2 wavy purple bags", "2 dim white bags"],
"dark black":["3 dim violet bags", "4 striped brown bags"],
"dotted purple":["4 drab red bags", "3 posh cyan bags", "3 dotted green bags", "3 dark green bags"],
"bright yellow":["4 muted coral bags"],
"pale teal":["1 vibrant yellow bag", "4 faded lavender bags"],
"light purple":["4 drab yellow bags", "5 plaid red bags", "5 wavy white bags", "3 bright olive bags"],
"mirrored lavender":["5 dotted beige bags", "2 dark coral bags"],
"wavy chartreuse":["no other bags"],
"pale purple":["2 posh plum bags", "3 dim silver bags", "5 vibrant chartreuse bags", "4 pale salmon bags"],
"dotted gray":["5 muted tomato bags"],
"vibrant maroon":["3 light red bags"],
"plaid purple":["5 bright magenta bags", "2 vibrant cyan bags", "4 drab maroon bags"],
"dim maroon":["3 dotted teal bags", "2 striped silver bags", "4 dim white bags", "4 pale purple bags"],
"posh lavender":["5 light magenta bags", "1 dim lime bag", "1 vibrant red bag", "1 light purple bag"],
"wavy tomato":["1 shiny tan bag", "4 plaid blue bags"],
"muted turquoise":["3 drab olive bags", "2 dotted beige bags", "2 wavy turquoise bags", "3 faded yellow bags"],
"shiny bronze":["5 dim black bags"],
"dim white":["5 dim purple bags", "4 pale red bags", "5 plaid lime bags", "5 striped silver bags"],
"faded maroon":["2 dark tan bags", "4 dotted olive bags", "2 striped gold bags"],
"muted silver":["1 plaid red bag"],
"dark salmon":["2 drab maroon bags", "5 posh green bags"],
"pale chartreuse":["5 dim violet bags", "4 muted aqua bags"],
"bright chartreuse":["5 shiny cyan bags"],
"plaid gold":["5 shiny chartreuse bags", "2 clear red bags", "1 bright yellow bag", "5 mirrored lime bags"],
"light lime":["4 dotted red bags"],
"bright tomato":["2 wavy orange bags"],
"wavy white":["3 striped white bags", "3 pale beige bags", "1 light plum bag"],
"mirrored gray":["1 dull gray bag", "4 plaid beige bags", "3 wavy turquoise bags", "1 pale maroon bag"],
"shiny purple":["2 muted maroon bags"],
"mirrored lime":["2 mirrored fuchsia bags", "5 dark lavender bags", "4 dull lime bags"],
"dotted tan":["2 pale maroon bags"],
"mirrored olive":["2 drab beige bags", "4 plaid crimson bags", "4 bright turquoise bags", "3 clear gold bags"],
"shiny salmon":["1 faded tomato bag", "3 drab white bags", "1 faded crimson bag"],
"shiny olive":["3 bright olive bags", "4 light orange bags", "1 pale maroon bag", "3 posh purple bags"],
"wavy aqua":["3 light brown bags", "3 dotted salmon bags", "3 vibrant brown bags", "1 dark beige bag"],
"bright bronze":["1 clear white bag", "3 clear cyan bags", "1 shiny black bag", "5 bright red bags"],
"dim lime":["5 drab lavender bags", "2 vibrant aqua bags"],
"dull cyan":["3 mirrored coral bags"],
"dark crimson":["5 faded yellow bags", "5 faded maroon bags", "3 faded magenta bags"],
"plaid silver":["2 dull maroon bags", "3 drab cyan bags"],
"plaid aqua":["1 wavy silver bag", "2 plaid orange bags"],
"bright black":["1 posh silver bag"],
"vibrant silver":["4 clear chartreuse bags", "2 pale brown bags", "4 pale orange bags", "2 light lavender bags"],
"wavy purple":["5 shiny tan bags", "4 dim brown bags", "4 faded crimson bags"],
"posh beige":["5 plaid olive bags", "2 dotted turquoise bags"],
"striped orange":["5 dark chartreuse bags", "3 wavy fuchsia bags", "4 wavy coral bags", "2 plaid indigo bags"],
"clear bronze":["1 faded orange bag", "5 shiny teal bags"],
"dull tomato":["5 muted gray bags", "5 muted brown bags", "4 dull teal bags", "2 plaid maroon bags"],
"plaid cyan":["5 dull plum bags", "1 clear red bag", "1 shiny salmon bag"],
"mirrored teal":["2 dim purple bags", "4 muted coral bags"],
"vibrant aqua":["1 clear gold bag", "1 dark red bag", "5 dull purple bags"],
"dull magenta":["2 dull lavender bags"],
"light maroon":["3 clear plum bags", "2 plaid olive bags", "5 dull blue bags"],
"wavy blue":["1 pale orange bag", "1 pale brown bag", "2 striped salmon bags"],
"bright crimson":["5 clear gold bags"],
"striped aqua":["2 bright brown bags", "5 faded tan bags", "3 wavy chartreuse bags"],
"muted gray":["1 dotted red bag"],
"posh coral":["5 vibrant gray bags", "3 faded teal bags", "3 dim lavender bags"],
"bright plum":["5 mirrored aqua bags", "4 shiny tan bags", "3 dim tomato bags"],
"shiny white":["no other bags"],
"plaid crimson":["3 faded gray bags", "3 wavy white bags", "1 faded lavender bag", "1 mirrored gold bag"],
"dull indigo":["3 shiny olive bags"],
"mirrored silver":["4 drab blue bags", "1 mirrored maroon bag", "2 plaid maroon bags"],
"dotted white":["3 dotted fuchsia bags", "5 vibrant aqua bags", "1 muted tan bag"],
"posh white":["3 light lavender bags", "1 wavy white bag", "4 dotted teal bags"],
"dim salmon":["5 muted magenta bags"],
"shiny blue":["5 light chartreuse bags", "1 shiny fuchsia bag", "4 muted bronze bags"],
"faded turquoise":["2 light silver bags", "4 dull salmon bags", "4 dim teal bags"],
"dim indigo":["1 dark bronze bag", "5 muted brown bags", "2 pale magenta bags"],
"bright salmon":["3 vibrant white bags", "2 dark tan bags"],
"clear violet":["3 shiny coral bags", "2 wavy purple bags"],
"posh crimson":["5 posh silver bags", "5 posh plum bags", "2 dull crimson bags", "3 posh blue bags"],
"faded salmon":["2 posh white bags", "5 mirrored fuchsia bags", "2 wavy fuchsia bags", "1 dotted tan bag"],
"bright cyan":["5 striped beige bags"],
"light gray":["5 dotted red bags", "1 faded gray bag", "3 bright olive bags"],
"mirrored green":["3 dotted lime bags", "2 dull salmon bags", "2 dim indigo bags"],
"dark tan":["2 pale green bags"],
"light tan":["4 dark coral bags", "3 clear indigo bags"],
"pale blue":["5 dull brown bags", "1 posh white bag"],
"clear chartreuse":["5 dim tomato bags", "2 vibrant crimson bags", "5 pale green bags", "4 shiny white bags"],
"wavy lavender":["5 posh gray bags", "2 dark olive bags", "4 drab yellow bags", "4 light blue bags"],
"faded olive":["1 bright yellow bag"],
"pale silver":["1 pale beige bag", "4 striped white bags"],
"clear cyan":["1 light green bag", "5 striped lavender bags", "4 muted bronze bags", "5 light yellow bags"],
"mirrored white":["3 shiny green bags", "2 bright silver bags", "2 posh black bags"],
"dark bronze":["3 dotted red bags"],
"faded gray":["5 faded crimson bags"],
"dull purple":["no other bags"],
"striped cyan":["4 dull purple bags", "1 shiny fuchsia bag", "3 striped green bags", "2 muted teal bags"],
"posh brown":["2 shiny gray bags", "1 dull teal bag"],
"bright blue":["4 wavy gold bags", "4 muted beige bags", "1 posh salmon bag", "1 vibrant yellow bag"],
"mirrored violet":["5 light plum bags", "4 plaid yellow bags", "2 dim brown bags", "5 clear tan bags"],
"wavy bronze":["2 drab blue bags"],
"muted purple":["4 muted olive bags"],
"dotted olive":["2 dull orange bags", "3 wavy gold bags", "3 bright olive bags", "5 pale green bags"],
"dark gray":["no other bags"],
"dim beige":["1 mirrored olive bag", "5 dim cyan bags"],
"drab green":["3 wavy gold bags", "2 clear gold bags", "4 dull cyan bags", "1 pale yellow bag"],
"clear lavender":["1 dull crimson bag", "4 pale red bags"],
"drab black":["3 bright white bags", "3 dim white bags", "4 light teal bags"],
"plaid coral":["3 light plum bags", "4 wavy aqua bags"],
"pale white":["5 light gray bags", "2 light indigo bags", "4 shiny blue bags"],
"drab lime":["3 dull lime bags", "2 dotted gray bags"],
"shiny green":["3 striped gold bags", "3 faded crimson bags"],
"light beige":["3 mirrored maroon bags", "1 bright magenta bag", "1 vibrant coral bag", "4 dull fuchsia bags"],
"striped lime":["5 dim magenta bags", "2 muted orange bags", "4 dull aqua bags"],
"shiny tomato":["1 dim blue bag"],
"pale gold":["1 clear indigo bag", "5 posh gold bags"],
"striped beige":["3 dark plum bags", "2 pale salmon bags", "1 striped white bag", "5 dull purple bags"],
"dull brown":["5 pale yellow bags", "4 pale silver bags", "4 pale red bags"],
"pale aqua":["4 posh silver bags"],
"shiny gold":["5 pale green bags", "5 faded gold bags"],
"muted tan":["2 vibrant red bags", "3 faded crimson bags"],
"striped red":["1 striped tan bag", "4 dim purple bags", "2 posh lime bags"],
"wavy red":["3 clear indigo bags"],
"light aqua":["3 light coral bags", "3 drab salmon bags", "1 bright lavender bag", "1 drab turquoise bag"],
"shiny brown":["3 bright indigo bags", "3 plaid beige bags"],
"striped maroon":["3 dim silver bags", "3 mirrored silver bags"],
"dim crimson":["3 wavy yellow bags", "2 pale lime bags", "5 dull magenta bags"],
"clear salmon":["4 dull fuchsia bags", "1 dull maroon bag", "5 light green bags"],
"dark green":["5 striped beige bags", "4 shiny gray bags", "1 shiny black bag"],
"vibrant red":["4 drab blue bags", "3 light plum bags", "1 posh orange bag", "4 dull silver bags"],
"dotted blue":["5 dull coral bags"],
"vibrant purple":["5 dull tan bags", "2 faded chartreuse bags", "4 light aqua bags"],
"striped yellow":["3 faded gold bags", "4 wavy gold bags", "2 pale brown bags", "1 light yellow bag"],
"pale magenta":["2 faded crimson bags", "3 striped violet bags", "3 vibrant chartreuse bags", "3 wavy red bags"],
"dull fuchsia":["1 pale brown bag", "5 dim purple bags", "2 pale gray bags"],
"wavy brown":["4 clear brown bags", "4 faded aqua bags", "4 muted tomato bags"],
"vibrant yellow":["3 dark tan bags", "3 light lavender bags"],
"light crimson":["5 shiny gray bags", "3 dim green bags", "3 dark black bags"],
"vibrant chartreuse":["4 plaid blue bags", "5 pale beige bags"],
"faded yellow":["5 wavy gold bags", "3 plaid bronze bags", "5 plaid red bags"],
"drab orange":["1 pale gray bag", "3 drab lavender bags", "3 dull lime bags", "1 wavy olive bag"],
"light chartreuse":["no other bags"],
"shiny cyan":["2 striped beige bags", "4 mirrored maroon bags", "4 dark yellow bags", "4 bright indigo bags"],
"dull aqua":["5 bright white bags", "3 dull coral bags", "1 faded yellow bag", "4 dull gray bags"],
"muted teal":["2 bright silver bags", "3 faded orange bags"],
"pale bronze":["5 posh teal bags", "3 drab indigo bags", "3 dim tomato bags"],
"vibrant salmon":["2 dull salmon bags"],
"plaid blue":["2 pale salmon bags", "2 dark gray bags"],
"faded beige":["1 vibrant plum bag", "4 light lime bags", "1 posh indigo bag", "4 posh brown bags"],
"bright aqua":["2 dotted plum bags", "1 dotted violet bag", "5 light orange bags", "1 muted chartreuse bag"],
"muted chartreuse":["3 plaid lavender bags", "1 wavy beige bag"],
"dark violet":["2 wavy crimson bags"],
"dull yellow":["2 plaid red bags", "2 striped brown bags", "1 wavy plum bag"],
"bright olive":["3 dark gray bags"],
"bright green":["4 muted aqua bags", "2 wavy tomato bags"],
"clear magenta":["5 plaid maroon bags", "2 vibrant teal bags", "3 clear indigo bags"],
"pale plum":["1 pale purple bag", "4 vibrant fuchsia bags"],
"plaid beige":["2 posh tomato bags", "3 mirrored maroon bags", "5 light purple bags"],
"plaid tomato":["4 dull gray bags"],
"posh fuchsia":["4 mirrored indigo bags", "4 faded salmon bags", "1 striped orange bag", "3 striped yellow bags"],
"dull salmon":["1 vibrant crimson bag", "4 muted olive bags", "3 dark brown bags"],
"striped brown":["1 dull coral bag", "3 shiny silver bags", "4 posh white bags"],
"drab plum":["5 wavy olive bags", "5 shiny tomato bags", "3 bright green bags"],
"vibrant tan":["4 pale beige bags"],
"bright turquoise":["4 vibrant teal bags", "3 dotted teal bags", "2 dark violet bags", "4 bright magenta bags"],
"wavy lime":["5 wavy green bags", "1 muted gold bag", "1 dim purple bag"],
"striped gold":["3 posh cyan bags", "3 muted coral bags", "3 wavy silver bags"],
"dull orange":["2 striped beige bags", "2 posh cyan bags", "2 shiny gold bags"],
"dotted lavender":["5 vibrant aqua bags", "4 bright turquoise bags", "2 drab turquoise bags", "3 dim aqua bags"],
"mirrored blue":["5 bright teal bags"],
"bright coral":["3 plaid salmon bags", "4 pale gray bags"],
"dark fuchsia":["2 vibrant aqua bags", "2 bright salmon bags"],
"pale fuchsia":["5 drab blue bags", "1 striped plum bag", "3 muted teal bags"],
"dotted indigo":["5 striped lavender bags", "2 bright cyan bags", "2 light gray bags", "3 plaid beige bags"],
"posh tomato":["3 dim red bags", "4 clear coral bags", "5 mirrored olive bags", "2 dull cyan bags"],
"dull silver":["2 plaid red bags", "2 faded silver bags", "5 mirrored maroon bags"],
"mirrored fuchsia":["2 bright magenta bags", "1 dark gray bag"],
"muted cyan":["2 mirrored teal bags", "3 dull fuchsia bags", "5 dotted olive bags"],
"shiny black":["2 shiny white bags"],
"dull crimson":["2 dim tomato bags", "1 clear chartreuse bag", "3 dull teal bags"],
"mirrored turquoise":["3 dull maroon bags", "1 shiny aqua bag", "2 mirrored violet bags"],
"plaid olive":["3 striped brown bags", "5 muted olive bags", "4 faded tomato bags", "1 vibrant teal bag"],
"posh lime":["3 plaid indigo bags", "2 light yellow bags", "2 pale blue bags", "4 bright maroon bags"],
"plaid plum":["3 muted orange bags", "1 dim tan bag"],
"dotted magenta":["1 mirrored teal bag", "3 light lime bags", "5 shiny tan bags", "2 vibrant coral bags"],
"dark gold":["2 muted orange bags", "4 mirrored yellow bags"],
"pale green":["5 striped white bags", "1 mirrored coral bag", "3 dark plum bags", "5 clear teal bags"],
"drab red":["1 vibrant coral bag", "4 drab lavender bags", "5 posh orange bags", "3 striped white bags"],
"posh green":["1 faded yellow bag", "3 light blue bags"],
"shiny lime":["1 pale beige bag", "1 dark silver bag"],
"plaid magenta":["2 light beige bags", "5 muted plum bags", "1 shiny coral bag"],
"posh salmon":["2 vibrant brown bags", "5 pale teal bags", "4 bright cyan bags", "4 shiny lime bags"],
"dotted orange":["4 plaid cyan bags", "5 light magenta bags", "3 dull chartreuse bags", "5 faded orange bags"],
"dull lavender":["3 vibrant gray bags", "5 vibrant magenta bags", "2 dim brown bags", "5 mirrored silver bags"],
"shiny indigo":["4 posh purple bags", "4 muted tomato bags"],
"light silver":["2 striped crimson bags", "5 striped turquoise bags", "5 pale black bags"],
"wavy crimson":["5 pale yellow bags"],
"dim purple":["4 bright cyan bags", "5 dark tan bags", "1 posh silver bag", "2 pale maroon bags"],
"mirrored cyan":["5 mirrored aqua bags", "4 dim tomato bags", "1 wavy gold bag"],
"wavy turquoise":["4 pale orange bags"],
"pale crimson":["5 light crimson bags"],
"drab olive":["5 shiny silver bags", "5 shiny white bags", "1 dark olive bag"],
"light violet":["5 posh lime bags", "4 dull salmon bags"],
"clear gold":["2 dark gray bags"],
"dark blue":["1 faded plum bag", "4 faded fuchsia bags", "5 clear red bags", "1 dull orange bag"],
"dim orange":["3 light blue bags", "1 faded orange bag", "1 dim fuchsia bag", "5 drab yellow bags"],
"mirrored tan":["3 mirrored gold bags"],
"posh purple":["2 posh silver bags", "1 dark brown bag", "3 dotted olive bags", "4 shiny white bags"],
"shiny coral":["4 bright indigo bags", "5 plaid teal bags"],
"faded fuchsia":["4 shiny maroon bags", "4 clear bronze bags"],
"plaid brown":["2 posh tan bags", "2 faded olive bags", "3 dull tomato bags", "4 dark plum bags"],
"faded coral":["3 light yellow bags", "1 pale red bag", "5 bright cyan bags", "2 dark coral bags"],
"drab gray":["5 light tan bags", "3 vibrant violet bags"],
"striped indigo":["5 vibrant tomato bags", "2 dull orange bags", "5 bright maroon bags"],
"dull red":["1 dark lime bag", "1 mirrored maroon bag", "3 vibrant white bags"],
"plaid indigo":["1 mirrored coral bag", "4 dotted red bags", "2 wavy chartreuse bags"],
"faded lime":["1 faded yellow bag", "5 faded gold bags", "4 faded aqua bags", "1 wavy tomato bag"],
"clear tan":["3 posh silver bags", "5 dull plum bags"],
"clear lime":["5 dull lavender bags", "3 faded magenta bags", "2 shiny olive bags", "1 posh orange bag"],
"dotted teal":["3 drab yellow bags"],
"wavy violet":["5 dotted beige bags"],
"faded bronze":["2 pale maroon bags", "4 pale silver bags", "4 mirrored fuchsia bags"],
"striped black":["4 dim silver bags"],
"wavy orange":["5 muted coral bags"],
"plaid violet":["4 posh turquoise bags"],
"muted violet":["3 plaid beige bags"],
"striped plum":["4 dark silver bags", "5 bright brown bags"],
"bright silver":["1 muted purple bag"],
"dim chartreuse":["4 wavy plum bags", "5 muted maroon bags"],
"faded orange":["2 pale maroon bags", "4 pale gray bags", "4 pale yellow bags", "4 faded tomato bags"],
"dotted black":["1 vibrant aqua bag", "3 posh black bags", "2 dim lavender bags", "3 pale coral bags"],
"vibrant gold":["4 dull chartreuse bags", "3 muted green bags", "1 shiny turquoise bag"],
"dull bronze":["1 dim salmon bag", "4 striped crimson bags"],
"clear blue":["2 clear coral bags", "5 vibrant chartreuse bags"],
"shiny tan":["1 shiny gold bag"],
"dotted brown":["5 dotted red bags", "4 shiny gray bags", "3 vibrant gray bags"],
"posh maroon":["5 dull coral bags"],
"drab tomato":["4 dull silver bags"],
"muted white":["4 shiny olive bags", "1 dull tan bag"],
"wavy teal":["2 wavy plum bags", "5 posh chartreuse bags"],
"shiny gray":["5 dull salmon bags", "1 dull crimson bag"],
"dim silver":["2 pale maroon bags", "3 plaid olive bags"],
"wavy magenta":["4 vibrant silver bags"],
"drab magenta":["4 muted olive bags", "5 dark chartreuse bags", "4 mirrored tomato bags", "2 bright magenta bags"],
"muted coral":["3 pale beige bags"],
"vibrant tomato":["1 vibrant plum bag", "4 bright black bags", "2 bright crimson bags", "5 faded turquoise bags"],
"vibrant white":["5 plaid blue bags", "4 dull cyan bags", "1 dull fuchsia bag"],
"bright brown":["2 shiny tan bags"],
"clear beige":["3 light lime bags", "1 faded turquoise bag", "4 mirrored salmon bags"],
"dull plum":["4 drab yellow bags"],
"light green":["5 vibrant yellow bags", "1 drab green bag"],
"wavy silver":["no other bags"],
"vibrant coral":["3 faded bronze bags"],
"light plum":["2 pale salmon bags", "5 dull teal bags", "1 dark plum bag"],
"pale orange":["no other bags"],
"dull gray":["1 vibrant crimson bag"],
"dull coral":["4 shiny white bags", "3 wavy white bags", "1 pale green bag"],
"muted bronze":["3 drab yellow bags", "1 dotted teal bag", "1 clear gold bag"],
"vibrant indigo":["3 dim violet bags", "3 pale yellow bags", "1 pale indigo bag", "5 shiny gold bags"],
"dark indigo":["4 light beige bags"],
"faded brown":["2 dim fuchsia bags", "5 dull turquoise bags", "1 plaid salmon bag", "5 light brown bags"],
"striped salmon":["1 muted olive bag", "2 dull purple bags", "1 dim tomato bag"],
"muted maroon":["4 plaid tan bags", "5 light gray bags", "4 pale turquoise bags", "3 faded maroon bags"],
"drab silver":["1 bright chartreuse bag", "3 plaid coral bags"],
"dim green":["1 plaid olive bag", "1 dim tomato bag", "3 muted aqua bags", "2 light gold bags"],
"light salmon":["4 muted orange bags"],
"bright teal":["5 striped gold bags"],
"dull teal":["no other bags"],
"bright maroon":["5 pale green bags", "3 pale brown bags", "2 posh purple bags", "3 light gold bags"],
"pale lavender":["5 dim beige bags", "5 shiny tan bags", "4 muted blue bags"],
"light turquoise":["5 mirrored olive bags", "4 striped maroon bags"],
"shiny beige":["5 dim bronze bags", "2 light gold bags", "4 drab beige bags"],
"clear olive":["1 mirrored olive bag", "2 muted orange bags", "3 faded salmon bags", "1 bright red bag"],
"shiny magenta":["3 wavy beige bags", "1 bright red bag"],
"pale indigo":["1 striped beige bag", "4 muted aqua bags", "3 muted olive bags", "1 dull teal bag"],
"vibrant fuchsia":["5 striped lavender bags", "2 dull orange bags", "4 striped beige bags", "1 posh silver bag"],
"wavy plum":["5 dull orange bags"],
"striped bronze":["4 bright lavender bags", "2 pale gray bags", "1 dull orange bag"],
"shiny aqua":["4 muted tan bags"],
"drab cyan":["4 clear plum bags"],
"drab turquoise":["3 dull tan bags"],
"striped coral":["3 striped brown bags", "5 bright yellow bags"],
"wavy coral":["4 dull teal bags", "3 vibrant fuchsia bags", "2 vibrant teal bags"],
"drab chartreuse":["3 drab blue bags", "5 vibrant fuchsia bags"],
"plaid red":["2 posh purple bags", "5 dull salmon bags", "4 vibrant fuchsia bags"],
"striped turquoise":["4 dotted beige bags", "4 vibrant crimson bags"],
"dark aqua":["4 dotted olive bags", "1 wavy orange bag", "5 dotted violet bags"],
"posh violet":["1 muted magenta bag", "5 mirrored magenta bags", "4 light chartreuse bags"],
"drab coral":["2 bright olive bags", "2 wavy tan bags", "1 dark aqua bag", "5 mirrored teal bags"],
"bright purple":["3 shiny teal bags", "4 faded tomato bags", "3 wavy plum bags", "1 wavy red bag"],
"dotted maroon":["5 mirrored teal bags", "5 dull gray bags", "3 vibrant yellow bags"],
"dotted crimson":["1 dim salmon bag", "4 clear gray bags", "4 wavy red bags"],
"plaid white":["5 pale salmon bags", "5 vibrant teal bags", "2 shiny coral bags"],
"dotted lime":["4 dark yellow bags", "1 dull lime bag"],
"shiny red":["1 bright brown bag", "2 plaid yellow bags"],
"clear purple":["4 mirrored olive bags", "5 light olive bags", "2 dark gold bags", "4 bright turquoise bags"],
"mirrored maroon":["4 muted aqua bags", "1 bright lavender bag", "2 bright cyan bags", "5 dull orange bags"],
"bright lavender":["3 pale brown bags", "1 striped gold bag", "4 pale chartreuse bags", "3 bright olive bags"],
"drab maroon":["1 pale orange bag"],
"muted crimson":["4 light gray bags", "2 muted white bags"],
"dark beige":["1 pale chartreuse bag", "5 pale gray bags", "4 shiny indigo bags"],
"clear silver":["5 mirrored gold bags", "2 muted brown bags"],
"dim turquoise":["5 faded orange bags", "4 dotted yellow bags"],
"dotted beige":["1 plaid teal bag"],
"dotted fuchsia":["5 posh tomato bags", "4 vibrant violet bags"],
"faded white":["1 wavy beige bag", "3 wavy white bags", "5 clear indigo bags"],
"plaid salmon":["4 light cyan bags", "5 drab lime bags", "5 muted green bags", "5 dim lavender bags"],
"striped lavender":["5 pale yellow bags", "1 dotted red bag", "1 plaid blue bag"],
"muted olive":["2 dark plum bags"],
"drab indigo":["3 vibrant chartreuse bags", "3 plaid teal bags", "1 dotted maroon bag", "5 dull lime bags"],
"bright gray":["4 faded indigo bags", "1 drab white bag", "3 muted blue bags"],
"dotted silver":["2 light green bags", "3 wavy coral bags", "1 bright chartreuse bag", "5 wavy violet bags"],
"vibrant magenta":["4 light indigo bags", "1 light lime bag", "3 shiny coral bags"],
"pale yellow":["5 muted aqua bags", "5 dark plum bags", "3 dark brown bags"],
"drab fuchsia":["5 faded cyan bags"],
"plaid orange":["2 dim silver bags"],
"plaid lavender":["1 pale maroon bag", "2 mirrored fuchsia bags", "4 striped yellow bags", "5 light lavender bags"],
"pale violet":["3 clear chartreuse bags", "4 posh black bags", "2 bright teal bags", "4 faded turquoise bags"],
"light white":["3 dotted indigo bags", "3 dull yellow bags", "3 plaid brown bags", "2 muted gold bags"],
"wavy cyan":["2 pale aqua bags", "4 dim cyan bags", "1 vibrant chartreuse bag"],
"posh orange":["1 pale beige bag", "2 dull coral bags", "4 pale chartreuse bags"],
"clear plum":["1 bright red bag", "2 dull tomato bags", "5 striped silver bags"],
"drab tan":["4 muted olive bags"],
"striped tomato":["3 posh orange bags"],
"muted beige":["5 mirrored violet bags", "1 dull orange bag"],
"mirrored purple":["4 muted olive bags", "5 dull lime bags"],
"light teal":["5 pale gray bags", "5 plaid lavender bags", "2 light plum bags"],
"dim teal":["2 striped beige bags", "5 pale aqua bags", "4 pale yellow bags"],
"dotted chartreuse":["3 vibrant lavender bags"],
"dim tomato":["3 bright cyan bags", "3 muted olive bags", "4 clear teal bags", "1 pale chartreuse bag"],
"vibrant teal":["2 bright red bags", "4 wavy chartreuse bags", "2 posh silver bags", "4 bright olive bags"],
"mirrored plum":["2 striped yellow bags", "2 striped lavender bags", "4 dark black bags"],
"plaid gray":["2 plaid teal bags"],
"vibrant gray":["1 dim brown bag"],
"drab salmon":["5 dotted red bags", "4 light gold bags", "3 mirrored maroon bags", "1 dotted plum bag"],
"dull lime":["3 shiny turquoise bags"],
"clear green":["4 plaid maroon bags", "1 dim crimson bag", "5 striped white bags"],
"dotted red":["1 dull teal bag"],
"faded purple":["3 shiny salmon bags", "3 clear tan bags", "3 bright magenta bags"],
"dark magenta":["1 dark tan bag"],
"mirrored red":["1 drab magenta bag", "3 wavy bronze bags", "5 shiny chartreuse bags"],
"dim blue":["2 light plum bags", "1 faded crimson bag"],
"dark cyan":["1 dull plum bag", "5 dim purple bags"],
"drab lavender":["3 dim purple bags", "2 dotted red bags"],
"posh red":["1 plaid lavender bag", "5 vibrant white bags", "1 bright magenta bag"],
"pale cyan":["2 striped yellow bags", "3 dotted red bags", "5 dull plum bags", "2 plaid blue bags"],
"pale black":["1 wavy beige bag", "1 clear magenta bag", "4 wavy red bags"],
"dotted aqua":["5 vibrant lavender bags", "3 muted brown bags"],
"clear brown":["5 posh brown bags"],
"light coral":["4 dull turquoise bags", "1 mirrored gold bag", "5 mirrored olive bags", "1 dull gray bag"],
"dotted bronze":["4 striped brown bags", "3 posh teal bags"],
"faded aqua":["1 dull yellow bag", "2 dark bronze bags"],
"dim magenta":["2 drab red bags", "3 clear tan bags", "1 faded lime bag"],
"clear fuchsia":["5 clear red bags", "3 plaid crimson bags", "4 bright magenta bags", "3 faded tan bags"],
"faded blue":["2 clear chartreuse bags", "1 vibrant crimson bag", "3 faded tomato bags"],
"dark tomato":["5 posh brown bags", "5 bright olive bags", "2 dull silver bags"],
"bright orange":["3 dotted teal bags", "5 posh orange bags", "5 wavy blue bags"],
"dim cyan":["5 dotted red bags", "2 wavy gold bags", "2 dull lime bags", "4 bright olive bags"],
"pale olive":["2 dull lime bags", "4 wavy white bags", "4 pale aqua bags"],
"dim lavender":["5 shiny green bags", "3 shiny cyan bags"],
"vibrant brown":["2 light magenta bags", "5 vibrant violet bags", "3 drab white bags"],
"striped teal":["3 clear salmon bags"],
"pale salmon":["5 dull purple bags", "1 dark gray bag", "2 dim violet bags", "4 shiny white bags"],
"wavy olive":["4 vibrant fuchsia bags", "2 shiny olive bags"],
"drab aqua":["2 shiny maroon bags", "1 pale orange bag", "5 wavy orange bags"],
"mirrored bronze":["3 dim blue bags", "4 drab chartreuse bags"],
"clear orange":["4 mirrored cyan bags", "1 striped red bag"],
"shiny fuchsia":["4 plaid teal bags", "3 vibrant coral bags", "5 shiny silver bags", "3 dotted red bags"],
"vibrant black":["5 light coral bags", "3 bright lavender bags", "1 dull violet bag"],
"dim yellow":["4 dark plum bags", "4 shiny coral bags"],
"shiny lavender":["3 dull tomato bags", "1 dark cyan bag", "4 light brown bags"],
"dull maroon":["3 light purple bags", "4 striped blue bags"],
"pale beige":["5 wavy chartreuse bags", "5 dull purple bags", "3 pale orange bags", "3 dotted teal bags"],
"vibrant plum":["3 dull turquoise bags", "3 shiny gold bags", "5 dark black bags"],
"clear tomato":["3 mirrored lime bags", "4 shiny red bags"],
"drab crimson":["1 clear silver bag", "3 wavy chartreuse bags", "3 pale bronze bags", "2 bright cyan bags"],
"posh bronze":["2 faded indigo bags", "1 clear red bag"],
"drab purple":["1 pale coral bag", "3 faded bronze bags", "2 striped yellow bags", "4 light orange bags"],
"muted tomato":["4 pale chartreuse bags"],
"dim fuchsia":["5 shiny white bags"],
"dotted turquoise":["3 drab plum bags", "3 pale olive bags", "4 posh silver bags"],
"posh chartreuse":["4 dotted indigo bags"],
"dim olive":["3 posh silver bags", "5 dotted beige bags", "5 light lime bags"],
"wavy gold":["5 muted aqua bags", "4 muted coral bags"],
"striped purple":["1 pale violet bag", "1 faded beige bag", "5 pale gray bags", "4 muted yellow bags"],
"faded cyan":["4 pale lime bags", "2 muted brown bags"],
"shiny plum":["1 muted purple bag"],
"faded crimson":["4 striped white bags"],
"wavy green":["5 dotted salmon bags", "3 dim fuchsia bags", "3 wavy aqua bags"],
"mirrored magenta":["3 drab black bags", "2 posh turquoise bags", "5 bright indigo bags"],
"dull green":["3 dull lime bags", "2 bright silver bags"],
"pale turquoise":["5 muted orange bags", "3 plaid bronze bags", "5 bright teal bags"],
"striped blue":["4 light lavender bags", "4 light orange bags", "4 muted coral bags", "5 wavy olive bags"],
"plaid fuchsia":["3 striped turquoise bags", "1 shiny bronze bag"],
"posh plum":["4 wavy silver bags", "4 vibrant crimson bags", "5 muted cyan bags"],
"faded tomato":["5 mirrored coral bags"],
"vibrant cyan":["4 muted green bags"],
"vibrant lavender":["1 dull tan bag"],
"faded teal":["4 dim red bags", "1 posh red bag"],
"plaid turquoise":["3 vibrant crimson bags", "4 striped yellow bags"],
"posh gold":["3 dull silver bags", "2 dark black bags", "3 faded lavender bags"],
"light blue":["4 shiny gold bags", "5 dotted beige bags", "1 dim brown bag", "2 shiny fuchsia bags"],
"mirrored chartreuse":["4 shiny tan bags", "2 dim purple bags", "2 pale cyan bags"],
"light cyan":["2 dotted olive bags", "2 dull crimson bags", "4 pale turquoise bags"],
"wavy yellow":["5 vibrant fuchsia bags", "3 drab fuchsia bags"],
"drab teal":["2 mirrored green bags"],
"bright red":["1 pale beige bag"],
}
end
